### ISSUE TITLE
getting started instructions fail to start app

### ISSUE THREAD

**Issue by rbavery** [eclipsesource/jsonforms-react-seed#124]
Running these: https://github.com/eclipsesource/jsonforms?tab=readme-ov-file#getting-started

Produces
```
# ryanavery at Ryans-MacBook-Pro.local in ~/jsonforms-react-seed on git:master ● [14:13:24]
→ npm run start

> jsonforms-react-seed@0.1.1 start
> vite preview --port 3000

/Users/ryanavery/jsonforms-react-seed/node_modules/rollup/dist/native.js:59
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/ryanavery/jsonforms-react-seed/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/Users/ryanavery/jsonforms-react-seed/node_modules/rollup/dist/native.js:68:76)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at cjsLoader (node:internal/modules/esm/translators:318:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:258:7) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/ryanavery/jsonforms-react-seed/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
      at Module._load (node:internal/modules/cjs/loader:1045:27)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
      at Module.require (node:internal/modules/cjs/loader:1304:12)
      at require (node:internal/modules/helpers:123:16)
      at requireWithFriendlyError (/Users/ryanavery/jsonforms-react-seed/node_modules/rollup/dist/native.js:41:10)
      at Object.<anonymous> (/Users/ryanavery/jsonforms-react-seed/node_modules/rollup/dist/native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1467:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1551:10) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/ryanavery/jsonforms-react-seed/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v22.4.1
```

**Comment by sdirix** [comment]
Hi @rbavery,
Can you try `npm install && npm run dev`?

**Comment by enersis-pst** [comment]
same error also with `npm install && npm run dev`
use node 20.0.0 on mac m1 pro

**Comment by rsoika** [comment]
I think there is something missing on the [getting started page](https://jsonforms.io/docs/getting-started)

To launch the app initially you need to run 3 commands:

```
$ npm ci
$ npm run build
$ npm start
```

I think this 2nd command should be added to the getting-stated page.

**Comment by lucas-koehler** [comment]
Thanks for the hint @rsoika , I opened a [PR](https://github.com/eclipsesource/jsonforms2-website/pull/306) on the website repo to fix this.
